# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build-linux:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            java: 17
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} for x86-64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build artifact
        run: ./gradlew jpackage jpackageAlt --info
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: Capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Ultreon Browser Linux DEB Build ${{ github.run_number }}
          path: build/dist/
  build-linux-armv7:
    # The host should always be linux
    runs-on: ubuntu-18.04
    name: Build on ${{ matrix.distro }} for ${{ matrix.arch }}

    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: armv7
            distro: ubuntu20.04
            java: 17
#          - arch: armv7
#            distro: fedora_latest
#            java: 17

    steps:
      - uses: actions/checkout@v2.1.0
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            artifact_name: git-${{ matrix.distro }}_${{ matrix.arch }}
            GITHUB_BUILD_NUMBER: ${{ github.run_number }}

          # The shell to run commands with in the container
          shell: /bin/sh

          # Install some dependencies in the container. This speeds up builds if
          # you are also using githubToken. Any dependencies installed here will
          # be part of the container image that gets cached, so subsequent
          # builds don't have to re-install them. The image layer is cached
          # publicly in your project's package repository, so it is vital that
          # no secrets are present in the container state or logs.
          install: |
            case "${{ matrix.distro }}" in
              ubuntu*|jessie|stretch|buster|bullseye)
                apt-get update -q -y
                apt-get install -q -y git openjdk-17-jdk
                ;;
              fedora*)
                dnf -y update
                dnf -y install git which openjdk-17-jdk
                ;;
              alpine*)
                apk update
                apk add git openjdk-17-jdk
                ;;
            esac

          # Produce a binary artifact and place it in the mounted volume
          run: ./gradlew jpackage jpackageAlt --info
      - name: capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Ultreon Browser Linux on ${{ matrix.arch }} Build ${{ github.run_number }}
          path: build/dist/
  build-macos:
    strategy:
      matrix:
        # Use these Java versions
        java: [
            17    # Minimum supported
        ]
        # and run on both Linux and not Windows
        os: [macOS-11]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew jpackage jpackageAlt --info
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Ultreon Browser MacOS Build ${{ github.run_number }}
          path: build/dist/
  build-windows:
    strategy:
      matrix:
        # Use these Java versions
        java: [
            17    # Minimum supported
        ]
        # and run on both Linux and not Windows
        os: [windows-2019]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: build
        run: cmd /c "gradlew.bat jpackage jpackageAlt --info"
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Ultreon Browser Windows Build ${{ github.run_number }}
          path: build/dist/